# Generated by Django 2.1.4 on 2018-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('progress', 'IN-PROGRESS'), ('done', 'DONE')], max_length=10)),
            ],
        ),
    ]
